/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/AppBackground.vue')['default']
    AppHome: typeof import('./src/components/AppHome.vue')['default']
    ContourBackground: typeof import('./src/components/common/ContourBackground.vue')['default']
    DebugPanel: typeof import('./src/components/tests/DebugPanel.vue')['default']
    OriginiumIcon: typeof import('./src/components/common/OriginiumIcon.vue')['default']
    PButton: typeof import('./src/components/PerlicaUI/PButton.vue')['default']
    PCheckbox: typeof import('./src/components/PerlicaUI/PCheckbox.vue')['default']
    PDivider: typeof import('./src/components/PerlicaUI/PDivider.vue')['default']
    PInputNumber: typeof import('./src/components/PerlicaUI/PInputNumber.vue')['default']
    PMarketCard: typeof import('./src/components/PerlicaUI/PMarketCard.vue')['default']
    PSpace: typeof import('./src/components/PerlicaUI/PSpace.vue')['default']
    PText: typeof import('./src/components/PerlicaUI/PText.vue')['default']
    SimulationResults: typeof import('./src/components/SimulationResults.vue')['default']
    UITester: typeof import('./src/components/tests/UITester.vue')['default']
    UserInputForm: typeof import('./src/components/forms/UserInputForm.vue')['default']
  }
}
